version: '3.3'

services:
  postgres:
    image: postgres:13
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - docker.env
    ports:
      - '5050:80'
    depends_on:
      - postgres
